### ISSUE TITLE
ob::Device::setStructuredData throws blank exception but appears to succeed

### ISSUE THREAD

**Issue by Suedocode** [orbbec/OrbbecSDK-dev#13]
I am writing a tool to enable the dhcp setting on devices with this simple code:
```
OBNetIpConfig config;
memset(&config, 0, sizeof(config));
config.dhcp = 1;
dev->setStructuredData(OB_STRUCT_DEVICE_IP_ADDR_CONFIG, (const uint8_t*)&config, sizeof(config));
```
I get this exception:
```
terminate called after throwing an instance of 'ob::Error'
  what():  Request failed, device response with error, errorCode: 1024, msg: 
```
I also read the dhcp setting and print it before attempting to enable it. After running this tool and terminating with the exception, **the dchp setting appears to have enabled as desired**, I'm just not sure what the exception is trying to tell me.

The OrbbecViewer produces the same error when enabling the dhcp setting, though it doesn't terminate on exceptions. However, disabling the dhcp in OrbbecViewer does not throw an exception. It's only when enabling dhcp that this message appears:
```
[10/16 00:53:20.573208][warning][19040][ObException.hpp:40] Request failed, device response with error, errorCode: 1024, msg: 
2024-10-16 00:53:20.573 ERROR [19040] [PropertyManager::write@531] write property failed: 1041@IP Address config, setStructuredData, exceptionType: 6, message: Request failed, device response with error, errorCode: 1024, msg: 
```

Environment:
Ubuntu 22.04.5 LTS (x86_64)
g++ 11.4.0
OrbbecSDK-dev https://github.com/orbbec/OrbbecSDK-dev/commit/bd2d4dd41d6214c9d8bfe3365efa865d5fe8df9f
Femto: Firmware v1.2.9

**Comment by hzcyf** [comment]
You are planning to change the DHCP-enabled IP configuration directly in the network connection state, right?

The problem should be that the firmware accepts the command and executes it immediately, making the network connection based on the old IP configuration unavailable and causing the SDK to fail to receive the response from the firmware.

I'll contact Femto Mega's firmware team about this issue and see if I can optimize it.

For now, you can just ignore the exception.

**Comment by Suedocode** [comment]
These error were produced over the USB interface. It's not a blocking issue though, and we can ignore it.

**Comment by hzcyf** [comment]
The Femto Mega firmware team has indicated that the errorCode: 1024 typically results from the device not being connected to a DHCP-enabled router or host. Once the device receives the DHCP configuration command, it will attempt to acquire an IP address from the router. If this process is unsuccessful, the error code will be triggered.

I have verified this on my end, and it is normal practice to first connect the device to the router before configuring it.

**Comment by hzcyf** [comment]
Close as it is not a issue.
